### ISSUE TITLE
Favorite buttons do not work

### ISSUE THREAD

**Issue by wakwak3125** [konifar/droidkaigi2018-flutter#63]
## Overview
- Favorite buttons do not work due to this error.

## Links
Is this information is useful to resolve this error?
https://github.com/flutter/flutter/issues/11231

@konifar Could you check the SHA configuration?

## Screenshot
<img width="834" alt="image" src="https://user-images.githubusercontent.com/10008419/36011716-93772b18-0d9c-11e8-87fc-07c9210263d5.png">

**Comment by konifar** [comment]
Thanks for creating the issue! I'll check it!
If I can resolve this, I'll give you a drink 🍺

**Comment by konifar** [comment]
@wakwak3125 Added fingerprint and fixed it!!!
Thanks a lot! 👍 👍 👍
